var ccb_resources = [
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'ccbi', src:"GameListLayer.ccbi"},
    {type:'ccbi', src:"GameListCellNode.ccbi"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"clickme.png"},
    {type:'image', src:"board.png"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'ccbi', src:"GameListScrollLayer.ccbi"},
    {type:'plist', src:"board.plist"},
    {type:'ccbi', src:"SignupLayer.ccbi"},
    {type:'ccbi', src:"GameListCellLayer.ccbi"},
    {type:'ccbi', src:"BoardLayer.ccbi"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
